name: CI/CD via GitHub Actions

on:
  push:
    branches: [ "main" ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.2.2
      with: 
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
              echo "Connected"
              cd ${{ secrets.APP_DIRECTORY }}
              git reset --hard HEAD
              git clean -fd
              git checkout main
              git pull origin main
              docker compose down -v
              docker compose up --build -d
